本节讨论这个部分最尖锐的部分——权力，也是社会这个系统中，最重要的话题。

权力在无形之间存在于我们的日常生活。让小区保安晚上帮忙开门，这是正常行使的权力；小孩犯了错，教育一顿这也是权力；在公司要求下属完成既定任务，这也是权力。

就像前面我们在讨论规则的时候，规则分为明规则和暗规则，权力也可以分为明权力和暗权力（其实，甚至知识也可以分为明知识和暗知识）。

所以权力还存在于我们意识不到的地方，也可以在有无之间转换。

比如，偶然的情况下，发现了你领导和其他同事而不正当关系，并掌握了证据。无形之间，权力的天平倾斜了，从明权力来说，你无法驱动你的领导完成什么事，但现在他却乖乖听你的。

权力的游戏就是如此诡谲。

《权力的游戏》中，有一段著名的对话生动地阐述了权力的本质。瓦里斯向提利昂·兰尼斯特提出了一个谜语：

"三个伟人——国王、祭司和富人——分别命令一个佣兵杀死另外两个。佣兵会听从谁的命令？"

这个谜语揭示了权力的相对性和复杂性。权力不是绝对的，而是取决于人们的认知和选择。在不同的情况下，权力的来源可能是政治地位（国王）、宗教信仰（祭司）或经济实力（富人）。

瓦里斯进一步解释道："权力存在于人们相信它存在的地方。这是一个幻觉，是一个笼罩我们所有人的影子。"

这段对话深刻地揭示了权力的本质。

权力是相对的，而非绝对的。它的存在和强弱取决于特定的情境和关系；权力源于人们的认知和信念。人们相信某个个体或群体拥有权力，这种信念本身就赋予了权力；权力可以来自多种渠道，如政治、宗教、经济等，不同的社会结构和文化背景会产生不同形式的权力。

=== 权力来源

权力总是左右人们的行为，人们的行为和善恶关系不大，取决于他们手中的筹码，筹码就是权力。

*规则 9.1：权力来自于博弈的结果。*

一对情侣躺在沙发上看电视，两人都有些口渴，但谁也不想起身去冰箱拿饮料。这时，一场微妙的权力博弈悄然展开。女生发话了 “不去给老子拿，晚上别想爬床上来”。这句话巧妙地利用了亲密关系中的筹码，瞬间改变了权力天平。男生权衡利弊后，不情愿地起身去拿饮料。

在这个场景中，女生临时获得了权力，而男生失去了权力。

同样的场景如果发生在结婚几十年后，可能就会反转。

那么这个场景的权力来自哪里呢？

在这个看似简单的日常互动中，权力的来源实际上是多方面且复杂的。首先，女生巧妙地利用了亲密关系中的筹码，即性资源，作为一种情感和生理需求上的权力杠杆。她通过威胁剥夺男生的某些权利来施加压力，这种负面激励成为了她权力的一个重要来源。同时，女生也抓住了男生可能更渴望亲密关系的心理，利用这一点来获得优势地位。

此外，在某些社会文化背景下，可能存在着男性应该更多地照顾女性需求的潜在期望，这种无形的社会压力也构成了权力的一种来源。

我们换个场景。在公司，一名中层领导，因为自己的失误而导致下属需要加班完成任务，虽然下属对其不满，但是依然加班工作完成了。

领导行使了他的权力，这是行政权力的作用。在企业的环境下，行政权的本质来自于人事权：录用人员、薪资和奖励的评定。

对于很多虚线领导来说，比如项目经理，没有赋予行政权，或者很少赋予行政权，推动项目是非常困难的。

这时候，这些项目经理只能寻求其它的权力来源。

比如：

- 可以通过评价员工在项目上的表现，这些表现能影响薪资和奖励的评定，间接的行使了人事权。
- 可以把工作安排的更加顺畅，员工工作起来更加舒心，从基层认同获得了权力。
- 可以和员工搞好关系，通过私人情感建立影响力，获得权力。

行政权和人事权，是来自上级赋予的权力；来自基层认同是群众支持得到的权力。

这两种权力有时候可能发生冲突，当公司的政策影响员工利益时，在秩序没有崩溃的情况下，管理者不得不使用上级的权力。

*规则 9.2：权力可以来自博弈的强势一方授予。*

当上级权力大于群众支持的权力时，讨好上级比照顾群众更能获得权力。

=== 非主流的权力

能力很强，为公司带来更多价值就能获得提拔，并授予权力，这是明规则。暗规则是，根据我们前面讨论的，群体利益和个体利益有时候可能并不一致。当领导并不需要在乎是否能给公司带来利益时，提拔他信任，或者对自己个人有利的人就变得合理了。

这些权力的来源是非主流的权力来源。这些非主流的权力来源可能是：

- 被掌握了秘密，被动放权。
- 资源交换，例如权色交易。
- 听话和忠诚。
- 提供情绪价值，会拍马屁。
- 亲戚和朋友等裙带关系。
- 破坏力。

想要找到这些例子太过于容易，就不在赘述了。

最值得讨论的一项特殊非主流权力来源是破坏力。这种权力源于个人或群体对组织造成潜在损害的能力，从而获得一定的影响力和决策权。

以软件行业为例，某个技术专家在一个项目中工作多年，积累了大量关键知识和经验。虽然他的技术水平可能并不出众，但他对项目的方方面面了如指掌。如果公司决定裁掉他，很可能会对项目造成严重的负面影响。因此，管理层不得不考虑他的意见和建议。

这位技术专家的权力来源颇为独特。他没有得到正式的领导授权，也并未掌握任何公司机密。他可能不善于服从或讨好上级，与管理层也没有私人关系。他获得影响力的唯一原因是：如果失去他，公司将面临重大麻烦。这种基于"不可或缺性"的权力，虽然不被正式承认，却在组织中发挥着实际作用。

通过“伤害力”带来的权力发生在各种地方。比如，在古代为官府办事的衙役按理说没有多大权力，因为公权力至少在县太爷级别的”官“身上，而衙役至少可以利用公权力拿人，不管合不合理，人们都需要孝敬衙役，这就是”伤害权“带来的权力溢价。

=== 权力的平衡：权责利一致

在有博弈资本的前提下，权力、责任、利益总是会趋向于平衡，这不算一条规则，只是算作一条规律。

这条规律，可以帮助我们去分析一些权力相关的问题。

举个例子，在一家公司中，如果领导委派你负责一个重大项目并提高了你的薪资，这时你有理由要求更多的决策权来确保项目的顺利实施。这体现了权力、责任和利益的平衡。

反之，如果领导给了你一个新的职位头衔，但你实际上无法做出任何重要决定，那么本质上你的权力和责任并没有实质性的变化。这种情况下，表面上的晋升可能只是一种形式，而非真正的权力提升。

这两个场景说明了权责利平衡的重要性。当三者不一致时，要么会影响工作效率，要么会导致职位虚化，甚至可能引发组织内部的矛盾。

权责利对等是一个分析权力的工具。


=== 权力的本质：生杀予夺

权力来源于系统中的位置，如果这个位置能对其它人产生生杀予夺的效果，那么就拥有了权力。

在金字塔结构的社会中，越是上层人士，越具备这样的能力，所以人们想尽办法往上层爬。

生杀予夺是权力的表现形式。

- 生：给予生存机会或提升地位。例如，领导可以决定是否录用一个求职者，或是否提拔一个员工。
- 杀：剥夺生存机会或降低地位。例如，公司高层可以决定裁员，或降低某人的职位。
- 予：赋予资源、权力或利益。例如，政府可以决定给予某些企业补贴或特殊政策支持。
- 夺：剥夺资源、权力或利益。例如，监管机构可以撤销某公司的经营许可，或者上级可以收回下属的某些决策权。

=== 财富是权力的度量值

把财富放到权力这一节有一些奇怪，但我放到一起的原因是，希望讨论权力和财富之间的微妙关系。

财富可以看做一种社会信用机制，它是社会成员之间互相权力流动的凭证，这种机制只有在秩序存在的情况下才能成立。

在猴群中，权力可以由猴王来行使和监督，决定如何分配食物和异性。

但在大型系统中，权力的拥有者无法做到这一点，于是智人演化出来货币用来记账，如何通过市场交易的方式流动某个人对整个社会的权力分量。

假设我拥有了一套房子，那么我可以行使这套房子的权力，把房子给一个朋友，他承诺使用其它的权力和我交换，在部落中，可能是一头牛，或者其它猎物。

这些权力无法量化和分割，于是人们找到了一些度量工具（货币）来衡量它们，一套房子的权力和交换多少头牛的权力。

货币贬值的本质，是统治者无形之间在收回物权，理解这一点就能理解社会经济系统的本质。

所以拥有多少金钱并没有太大意义，有意义的是金钱的相对值，以及获得金钱的方式。如果每个人都是千万富翁，那么在一个封闭小区中，百万富翁就不得不去承担人们不愿意的工作，放下百万富翁的段位去清掏化粪池。

换句话说，金钱是可支配社会资源的量化。

那么这也可以回答什么是价值？

价值其实和劳动无关，价值是人们对权力分量的评价。价值取决于需求，而与产生这些价值的实际成本关系并不大。

比如在盐铁专营的时代，盐的社会价值远远超过了生产它的成本，因为本质是政府行使权力的工具，人们支付给盐的金钱大部分都需要上交，本质是一种特殊的税收。

而在封建帝国时代，政府的权力来自于暴力，以及长期稳定的秩序下民众的认同。
