== 如何深度分析一个问题？

这是及其难写的一篇，因为深度认识问题的过程是无止尽的，我们只能不断接近问题的本质。且远远不止有一种方法可以分析问题，看待问题的深度决定了一个人解决问题的能力。

我只能尝试用我自己的理解，介绍几种分析问题的方法，希望对大家有所启发。深度分析问题是咨询工作必不可少的能力，一般面试也常常会考察这方面的能力。

大多数的问题都不是表面上看到的那么简单，问题的背后往往隐藏着更深层次的原因，否则问题就很容易解决。之所以问题会变得复杂，是因为问题的背后往往隐藏着更深层次的原因，这些原因往往被问题的表象所掩盖。

对于很多历史爱好者来说，历史事件就是深度问题分析的素材。

例如在历史上，引发战争的导火索是压死骆驼的最后一根稻草，但真正压死骆驼的却不是最后这根稻草。

1914年6月28日，奥匈帝国皇储弗朗茨·斐迪南在波斯尼亚首府萨拉热窝被一位塞尔维亚民族主义者刺杀。这看似是一起单纯的刺杀事件，导致了奥匈帝国对塞尔维亚的宣战，进而触发了第一次世界大战。

但问题远比表面复杂，奥匈帝国内部民族矛盾尖锐，塞尔维亚民族主义者主张南斯拉夫民族统一，反对奥匈对南部斯拉夫地区的统治。

与此同时，欧洲列强形成了两个军事集团：三国同盟（德国、奥匈、意大利）和三国协约（英国、法国、俄国）。一个国家的冲突会迅速扩大，最终导致世界大战。

各国都在扩张势力范围，军备竞赛导致战争一触即发，许多国家早就做好了开战的准备；各国高估自身盟友的支持与敌方的忍耐程度。比如德国对奥匈的“空白支票”支持，俄国对塞尔维亚的无条件保护。

表面上，一个刺杀事件似乎是战争的起因；实际上，它只是点燃整座火药库的一根火柴。真正的问题是长期积累的民族矛盾、政治联盟、帝国主义扩张、以及各国精英的傲慢与误判。

=== 重新定义问题

有一些问题被重新叙述后，问题就变得简单了。语言的边界就是思想的边界，如果不能用语言准确描述问题，就无法准确理解问题。

分析问题的第一步是先定义问题。虽然这句话很傻，但是在很多情况下，我们并没有真正理解问题。

在软件产品设计领域，此类场景非常多见。举个例子，在订单列表中需要查询每个订单的物流状态。

产品经理给出的需求是在订单列表中增加一个字段，显示每个订单的物流状态。但是，如果仔细分析，就会发现这个问题并不简单。因为每个订单的物流状态，需要调用物流公司的 API 循环查询，导致列表页的性能比较低。

当我们把问题表述为：给订单列表增加一个物流状态的字段。在技术上其实有很多制约，或者说非常不划算。

如果我们把问题重新定义为：用户在订单列表可以查看每个订单的物流状态。其实这个问题才是我们真正需要解决的问题。

**你会发现一个规律，当我们越把问题描述得像解决方案，我们探索的空间就越小。**

如果我只是为了让用户能看到物流状态，那么其实有很多解决方案。比如我可以在订单列表中增加一个按钮，点击按钮后，会弹出一个模态框，显示每个订单的物流状态。

这样避免在页面加载时就调用大量的 API 查询，不仅实现起来稍显复杂，同时也会带来性能问题。所以我们在定义问题的时候，需要分清楚目的和手段。

**目的：用户在订单列表可以查看每个订单的物流状态。**

**手段1：给订单列表增加一个物流状态的字段。**

**手段2：在订单列表中增加一个按钮，点击按钮后，会弹出一个模态框，显示每个订单的物流状态。**

通过追问问题的本质，定义真正我们需要解决的问题，这就是 X/Y 问题。

XY 问题是指你把自己的问题错误地描述为解决方案的问题。换句话说，你把自己想要实现的结果或目标（X）通过一个错误或不理想的手段（Y）来表达，导致其他人只能聚焦在如何解决 Y 上，而不是本质问题 X。

我们经常犯的错误：

- 把问题的解决方案当作了问题本身。
- 无法全面考虑其他解决方法。
- 导致别人关注点偏离真正的需求或核心问题。

结果导致讨论方向变得偏离目标，可能浪费时间或精力。为了避免 X/Y 问题，我们需要先定义问题，然后再定义解决方案。

这时候我们需要使用第一性原理（First Principle）。第一性原理来自苏格拉底和勒内笛卡尔的理性主义分支，这是一种关于“追问”的艺术。

=== 第一性原理（First Principles）

第一性原理（First Principles）是指从最基本、不可再分的事实出发，跳出传统思维框架，以一种更根本、更基础的方式思考问题。其核心是：从最基本的假设出发，重新构建对问题的理解。

并不能说第一性原理就多厉害，而是不同的一个视角。

我们把从问题到解决方案的过程想象成一个漏斗，探索问题的过程也不断收缩，如果我们只看到解决方案，那么也意味着潜在的解决方案被我们忽略了。

我们根据直觉、他人的建议、历史经验自动否定了潜在很多可能性，这得益于我们大脑喜欢缓存结论的机制，这很省电，但往往让问题变得复杂。

例如，我们花费大量的精力研究汽油车、变速箱，把汽车烧油当作一种理所当然的事情，但真正的问题是如何让汽车跑起来。

所以从第一性原理出发，把如何造出更好的变速箱的问题，变成如何造出更好的汽车的问题。于是，电动车的设想可以被放到台面重新讨论。

想象一个坐标轴，左边是问题，右边是解决方案，X/Y 问题和第一性原理，让我们能意识到有这个坐标轴的存在，从而让我们能从不同的视角看问题。

=== 用矛盾的视角看问题

通过矛盾分析问题，是辩证法的基本方法，来自《毛选》中的《矛盾论》一篇。

矛盾分析法，就是将问题分解为矛盾，然后分析矛盾的性质、矛盾的双方、矛盾的转化要素来进行分析。

矛盾的几个特点：

1. 矛盾的普遍性：矛盾无处不在，无时不有。
2. 矛盾的特殊性：不同的矛盾有不同的性质、矛盾的双方、矛盾的转化要素。
3. 矛盾的同一和斗争性：矛盾的双方在一定条件下可以相互转化。

这几个特点有点绕，说的通俗一点，矛盾在哲学上是指事物内部或事物之间的对立统一关系。所以我们看待事物需要相对、辩证的看待，万事万物的发展是因为有矛盾的存在，否则事物就会达到平衡和静止。

比如手机掉落到湖里，是因为重力和浮力，重力是向下，浮力是向上，这两个力的大小决定了手机是沉到湖底还是浮在水面上。

重力和浮力可以看作是矛盾的双方，它们的大小决定了手机是沉到湖底还是浮在水面上。

重力大于浮力所以推动手机掉落，而掉落到湖底是手机和湖底之间的矛盾，手机和湖底之间的矛盾是手机和湖底之间的相互作用力，这时候矛盾开始转化，湖底的支撑力和手机自身的重力开始平衡，手机就静止在湖底。

没有矛盾的推动，事物就会达到平衡和静止。

通过矛盾分析的主要难点在，矛盾的参与方往往不是单一的，而是多个，比如手机和湖底之间的矛盾，手机和湖底之间的矛盾是手机和湖底之间的相互作用力，这时候矛盾开始转化，湖底的支撑力和手机自身的重力开始平衡，手机就静止在湖底。

所以我们需要分析在某一刻，主要矛盾是什么？次要矛盾是什么？有时候主要矛盾容易被藏起来。

我们来换一个例子。一名学生学习成绩不好，随着时间推移，成绩越来越差，最后被学校劝退。

这是什么原因？是智力问题？是学习方法的问题？是家庭教育的问题？是学校教育的问题？是社会问题？是心理问题？

我们用矛盾分析法来分析这个问题。我们可以假设这些一些矛盾，并通过调查研究，找到问题的根源。

比如我们假设智力问题，那么我们可以进行智力测试，如果测试的结果显示智力正常，那么智力问题就不成立，或者影响程度很小，不是主要矛盾。

随着调查研究的深入，我们发现这名学生花了大量时间玩游戏，并没有好好学习。那么推动学生成绩下滑的主要矛盾就是：学生学习时间投入不足和日益增长的学习难度之间的矛盾。

那么通过矛盾分析问题，在操作上有两个难题：

- 寻找主要矛盾：在一堆矛盾中，哪一个是主要矛盾？
- 寻找背后的矛盾：在主要矛盾的背后，是否还有更深层次的矛盾？

这两个问题，就是接下来需要分析的内容。

=== 动态分析：系统和反馈

到目前为止，问题的分析还是静态的。我们还需要动态的分析问题，也就是系统的分析问题。

我们处于一个复杂的系统中，所以受到《控制论》的支配，控制论描述了系统如何被影响和变化。

控制论有两个重要的概念，可以帮助我们分析动态的问题。

- 正反馈：输出增强输入，使变化被放大。例如滚雪球效应和金融市场的泡沫。
- 负反馈：输出抑制输入，使系统趋于稳定。例如人体体温调节。

正反馈会放大问题，负反馈会缩小问题；同时，正反馈会趋向于震荡，负反馈会趋向于稳定。

比如从宏观来说，房地产市场是一个正反馈系统，当房地产价格上涨时，需求会增加，导致价格继续上涨，形成恶性循环，并在一定时间泡沫破灭。

而没有其他投资属性的普通商品的价格趋势就是一个负反馈系统，当价格上涨时，需求会减少，导致价格下跌并保持平衡。

在生活和工作中，识别到正反馈现象，可以帮助我们解决问题。比如，软件研发团队因为时间紧迫，导致工作流程不严谨产生了很多Bug 和生产问题，这些问题压缩下一个迭代的时间，导致时间更加紧迫，这是一种正反馈现象。

只需要想办法切断反馈链条，就有办法解决这些问题。

=== 挖掘背后的利益相关性

另外，很多问题都不是表面上看到的那样，如何深度分析一个问题，一眼就能看到本质？

电影《教父》里面有一句经典的台词“能花一秒钟看透事物本质的人，和一辈子都看不清事物本质的人，注定是截然不同的命运”

我之前分享过 “你以为是一个技术问题，其实是一个利益问题；你以为是一个利益问题，其实是一个政治问题” 就是一个例子。

某知名酒厂花了很多钱搞信息化，结果发现连基础的库存管理系统都不愿意用？为什么因为，如果管理太精细，就没法从中混到油水，所以为这个酒厂做数字化改造的公司赔了一大笔钱黯然离场。

我们经常遇到类似的问题，你以为接的是一个培训，实际上接的是一个以培训打分为目的，把阻碍信息化变革的基层领导全部换掉。

我把深度问题分析整理成两个要素：

1. 足够有效的信息来源 （其实难在这里，真正有效的信息往往是金钱传播和性传播的，把送礼和发红包养成习惯）
2. 良好的推理框架，从有效的信息获得正确的结论（后面说的框架）

常见深度问题分析的框架有这么几个：

- 矛盾论：分析主要矛盾和次要矛盾，找到主要矛盾，屏蔽噪音
- 第一性原理：从基础原理出发分析，剥离表象
- 苏格拉底式提问：持续追问，直到无法回答
- 结果反推法：从期待的目标反过来推导，例如我想涨粉，反过来一步一步推导需要做什么

咨询公司提供的往往是推理框架，以及为推理框架背书，信息来源往往是购买咨询服务的人内部提供。

////

这里的内容可以留在未来整理

=== 其他分析问题的方法和线索

- 寻找主要矛盾：循证分析和量化分析
- 寻找背后的矛盾：根因分析
- 跳出框架，将自身置于问题之外 

////
