== 如何对目标上瘾，获得执行力？

如何把一件事坚持下来，是成事的重要因素。

把事情做成总结下来有两个要素：

1. 方向是否正确，这个我们前面两节已经讨论过。
2. 是否具有足够强的执行力，这正是本节的目的。

在很多时候执行远远比创意、点子重要，因为只有在执行过程中才能不断反馈，不断调整方向，并深入认识到问题。所谓知易行难，执行比问题分析、方向判断更难。

同样的一个点子，不同的人来执行可能会获得不同的结果。不仅是因为具备的资源不同，很重要也在于执行力的差异。

我们始终得承认，人是一个动物，所以执行力也具有生理基础，这是一切理论和叙事的前提。

所以我们需要思考一个问题：人为什么会主动做一件事，并坚持做下去？

在神经生物学中，答案非常简单：奖励。

我们容易陷入一个矛盾的情况，对有些东西需要坚持，对不好的习惯却又难戒断。不喜欢学习是人的常态，酗酒、游戏上瘾也是人的常态。

所以我们能不能像酗酒、游戏上瘾一样对学习、赚钱、健身上瘾呢？

这还真是可以的，答案就是奖励这一个生理基础。

在由多巴胺主导的奖励回路中，有几个重要的脑部区域参与了：

- 腹侧被盖区：多巴胺神经元起点。
- 伏隔核：奖励信号的“放大器”。
- 前额叶皮层：控制、延迟满足、理性判断。

我们的理性产生在前额叶皮层，然而我们的奖励和快感却主要由腹侧被盖区和伏隔核提供，这就导致了前额叶不够强的情况下我们非常短视、做不到延迟满足。

1954  Olds & Milner 做了一个“快感按钮”实验。给老鼠在脑内植入电极，老鼠可以通过按杆刺激某个脑区（伏隔核附近），老鼠可以一小时按压上千次，放弃进食、睡眠，直到按到力竭死亡。

这种作弊的奖励回路被激活，会让老鼠在没有任何奖励的情况下，持续地做下去，无视理性中枢的判断和管理。这正是毒品、赌博、短视频的共同点

我们之所以无法坚持某项任务，是因为在短期来看，无法获得该项任务的奖励，让人产生快感，从而驱使自己的身体产生行动。比如学习编程，如果短期无法看到效果，或者利用这个技能赚到钱，大部分人就会很快放弃。

实际上，人类的大脑对于“想要”和“喜欢”是分开的，有科学家做实验操纵老鼠多巴胺系统，测量行为动机（是否愿意付出努力）和实际愉悦反应（面部表情）。会发现一个有意思的结果，老鼠依然“喜欢”甜味食物，但是并没有表现出追求的行为动机。

这就是我们人类的困境，没人不喜欢钱，但不是所有人都有赚钱的动力和执行力。我们之所以无法采取行动，这取决于回报周期是否足够短，和回报的确定性足够大。

有意思的事，这个心理被用到销售成交上同样适用。人们之所以会付钱购买一件产品，本质上是因为回报，只要花了钱得到的回报确定性足够强、回报周期足够短、回报足够诱人人们就会付款。

=== 让反馈和奖励回路更短

想要解决执行力的问题，最直接的方案就是让反馈和奖励回路更短。

这也是电子游戏设计的基本原理——设计一个大多数人刚刚好能通过的关卡。否则玩家会因为无法通过关卡，导致无法再游戏中获得奖励，从而放弃游戏。

电子游戏之所以容易上瘾，就是因为他能比现实生活更容易获得奖励。在现实中赚一万块钱付出的劳动和困难程度远远超过在游戏中获得新装备的成本。

如果我们把一个困难的目标进行拆解，就能快速获得奖励。

对于学习编程的人来说，如果需要花上两个学习的辛苦学习语法知识才能在黑洞洞的命令行窗口中看到程序运行效果，对大多数人来说就都是不友好的，这也是为什么大学的计算机教育如此失败的原因。

更科学的方法是选择能快速获得反馈的编程语言，在第一次实验课程中就能体验到编程乐趣和魔法的效果。所以以 Javascript 为主的前端开发就非常适合入门，相比 C/C++，所见即所得的网页开发能快速建立反馈和奖励回路。

我认识一个朋友，通过 Cursor 等 AI 工具快速实现了一个提词器工具解决了录制课程的痛点，很快就爱上了学习编程。

在传统教育中，孩子讨厌学习的本质也是无法及时从学习中获得反馈和奖励。学习了很多的知识无法联系到现实问题，进而获得反馈，这不符合人的认知习惯。

另外在心理学上，多次小的奖励比一个大的奖励更有效果，这是人的生理基础决定的。比如，把一个月一万的工资，分成十次发放给你，你会获得更多幸福感，虽然收到的钱还是一样。

=== 让回报和任务更加清晰，尽量消除模糊

想要让奖励强度更大，就要让回报和任务更加清晰，尽量消除模糊。比如打工和做生意相比，打工确定性更强，所以大部分人都会打工。

你找人谈合作，有很多人没看到钱的时候理都不会理你，然后看到有“钱景”，然后主动找你，这就是确定性带来的执行力。

马斯克说过一句实在话：“我从来都不相信这个世界上有什么行动力不足的事情！因为所有行动力的问题，其实都来源于精确性的不足。”

更完整的说法应该是回报的精确性不足，如果我知道精确的知道没有回报也不会有行动。

在工作中很多人的拖延症，本质问题就是不知道怎么干，不知道老板或客户要的东西长什么样子。于是花了大量的时间在不重要的事情上，继而也没有动力做下去。

比如写一篇文章。如果你已经知道这篇文章的内容、结构、素材，那么获得写完这篇文章的成就感是很强的，可能熬夜都会想着快速把文章写完。

但如果脑子中只有一个模糊的想法，那么这篇文章就很难被完成。所以如果写文章有一个固定的模式，比如观点、材料、论据，写文章就没那么难被执行了。

我曾经分享过一个写文章的模式，写一篇文章只需要三个固定的步骤：

1. 收集或者想到的一个观点。
2. 寻找一个合适的例子，像讲故事一样讲出来。
3. 查询一下有没有相关理论或者名人的论证，支持这个观点。

通过这个固定模式，就能快速写出大量的文章来，而且质量都不会很差。

所以提高执行力的方法就是从交付物反推任务，让任务变得具体、清晰和可以容易被执行，这样执行力就提高了。

比如，在咨询公司经常需要对一些软件系统进行调研评估，对于没有经验的人来说执行起来是非常困难的。

但是如果你参考了大量的咨询公司报告，然后通过交付物倒推任务，就会发现任务是非常具体和清晰的。

比如咨询公司往往输出一个软件系统的健康度评分，根据不同的维度产生一个雷达图，并输出这个系统的亮点和潜在风险。关键的地方在于，这个报告需要富有逻辑。

那我们来拆解一下任务：

- 我需要评分和产生雷达图。
- 所以我需要一个评估框架，包括几个重要评估维度（架构、运营、文档、质量等）。根据这些维度拆解出具体的评估指标（比如架构是否符合微服务架构、运营是否有监控系统、文档是否完善等），以及如何评分的打分条件。
- 最后根据这些指标，我需要一个评分系统，能够根据指标的得分，产生一个最终的健康度评分和雷达图。

如果是有经验的咨询师，可能会已经有一个评估框架，执行力会更强，但是对于没有干过的人来说，从交付倒推任务，是提高执行力非常重要的方法。

否则，你会在和交付物无关的事情上来回打转，看看这、看看那。

=== 节约使用注意力，尽量避免多线任务

注意力对执行力来说非常宝贵，要有所取舍。很多人执行力很强，但是做的事情太多了，以至于每件事被稀释，或者遗忘了。

对于大多数人来，大部分事情都是没有意义的——不做，基本上也不会有什么影响。所以提高执行力的方法就是把时间花在真正价值高的事情上，而不是感觉价值高的事情上。

关于注意力的问题，我会在后面专门一节讨论。

=== 利用沉没成本心理

利用沉没成本心理构建执行力驱动力。人们的沉没成本心理是舍不得放弃，投入越多，陷入越深，然后反过来用。

比如一个证书需要 3 次考试，1000 块钱费用。如果你没参加考试，也没花钱，那么很容易放弃。

如果你已经支付了 1000 块钱，就有了沉没成本，就很难放弃了；如果你通过了两门，那么无论如何也很难放弃这个证书了。

所以付费报名课程，往往比自己自学能更容易通过考试，也是这个原理。

沉没成本心理对人的心理还有更大的影响力，甚至会因为沉没成本修正对某个问题的态度来合理化自己的错误决策。

假设你爱上了一个不合适的人，随着投入变多，大脑为了让自己的决策更加合理，会不断找借口为什么喜欢TA。

=== 节奏和监督机制

大部分人没有自驱力，所以很多时候搞自己的事很难成，但是公司老板给予压力就能搞成。

这也是为什么很多高管在有公司平台的时候能做出成绩，然后自己出来就一塌糊涂；小孩暑假在家不愿意做作业，而到了学校就能写作业。

这里面有很多原因和技巧也能用到提高执行力上：

- 监督机制
- 环境和氛围、同侪压力
- 习惯

利用这几个技巧，可以让个人的执行力产生质的飞跃。

很多大 V 搞陪伴群，本质就是一种监督机制，通过群里的互动，强制要求成员按照一定的时间和频率完成任务。主动花钱买不舒服和鞭策，侧面印证了想要和喜欢是两回事。

如果想考研就去自习室、如果创业尽量还是搞个办公室，在家里办公还能做出成绩不是所有人都能做到。

在监督机制上，增加环境和氛围的影响，和一起工作学习的人产生竞争，会让执行力又上一个层次。正所谓，即害怕兄弟过得苦，又害怕兄弟开路虎。环境和同侪竞争也是来自人性的底层密码。

在监督和环境的影响下，持续一段时间，养成了习惯，执行就变成了吃饭喝水一样自然，甚至不做都会不舒服，这是神经回路不断被强化的结果。

如果你是站在管理者的角度，培养团队的执行力，这几个要素也可以发挥作用。反之，在组织中，如果不注意这几个要素，就会出现执行力滑坡。

监督机制这个就不谈了，没有公司不存在监督机制，否则所有人都会划水；而环境和氛围中，同侪压力也非常明显，当一名员工没有执行力的时候，不需要惩罚，只需要奖励他的同事就行了。

人不患寡，而患不均。比如绩效达标的员工，奖励一次旅游，那么没有绩效达标的人就会被驱动。有时候甚至只是口头的表扬就会触发同侪压力。

同样的，在组织中把所有执行力相关的制度、监督和奖励机制培养成团队习惯后，这就是大家经常说的团队文化。

所谓团队文化，就是人们耳熟能详、自然而为的信念和习惯。
