== 我们为何羞耻？羞耻是规训的结果吗？

羞耻感会给人带来很多问题，不敢上台演讲、不敢表达和交友。

很多时候我们会认为好像羞耻就是人的天性一样，所以把人分为内向、外向，或者更多的性格类型。

这是真的吗？

成年人会对很多东西感到害羞，觉得暴露隐私部位、异性接触、偶尔犯错、大声讲话都是一种羞耻的行为。但是还没有接受教育的儿童却不会表现出感到羞耻现象，大方的接触其它的小伙伴，虽然可能会表现出害怕，往往不会表现出羞耻感，甚至不穿衣服满大街乱跑。

每个人对待羞耻的程度也是不同的，有些人一回家就放飞自我；有些人穿稍微暴露一点的衣服都不好意思；有些人为了成为网红，在接头搞什么“社死”的行为艺术。

那么羞耻到底是怎么回事呢？它真的是天性的一部分吗？

我们还是尝试寻找进化意义上的原因。

=== 羞耻的来源

为了解释羞耻，我先讲一个故事。

一群原始人平常获得食物并不容易，全靠运气。有一天大家齐心协力打到一头麋鹿，按照族群的规矩，他们不能马上吃这头麋鹿，需要交给部落领袖分配。

但天色已经很晚了，他们把这头麋鹿放到部落存储食物的地方放了起来。

部落中的某个人，对这头麋鹿垂涎三尺，于是晚上割走了一个鹿腿，但不小心被看守的人发现了。

这件事传到了部落中，人们对偷走麋鹿肉的人大吐唾沫星子。由于原始人的部落人力宝贵，领袖并没对他实质性的惩罚，只是给绑在村口示众一日。

人们见到他就问候祖宗十八代，因为他损害了集体的利益。

“你这个不要脸的，悄悄的偷吃麋鹿” 人们会这样指责他，部落中的其它人都会给他戴上一个偷麋鹿的人的帽子。

部落中的其他人害怕自己也被指责，所以偷吃麋鹿就变成了令人不齿的行为。

其实我们日常对待羞耻的态度也是这样，如果我做了一件事，所有人都批评，那么我对这件事就会产生羞耻感；如果这件事被大家称赞，那么就不会感到羞耻。

羞耻是一种对人们指责的畏惧。

在社会中，我们必须遵守社会规则，所以父母从小就会通过规训来教育幼童，从而产生羞耻感。羞耻感来自社会、家庭的不断地规训教育，但人们忘记了它的来源。

有时候羞耻感的培养过度了，又会指责幼童为什么这么怕羞，这会产生一些矛盾场景。

父母为了孩童的安全，不让他和陌生人说话，于是小孩害怕被父母指责，就不敢对陌生人说话，这是一段非常合理的神经回路。

同样的，当小孩说错话（对小孩来说并没有对错的概念，只是不符合成年人的认识），家里的人可能会批评他，这样他形成了“说错了话会被批评”的神经回路，自然不敢公开说话了，因为害怕说错了话，会被老师和其他小朋友批评、嘲笑。

所以有些科学家把羞耻看成是一种规训，人类文化早期就产生了羞耻，目的是防止部落的人越过规则获取资源，包括食物和性。

弗洛伊德认为，羞耻是一种内心冲突的表现，源于个体对自我行为或思想不符合社会规范的内在批判。他的理论强调了羞耻感是由于潜在的罪疚感和对社会道德标准的内化。

性，对于任何文化都是稀缺的，即使物质发达的今天。被成功选择下来的组织，往往是约束个体的那一类，性在这些文化中就成了禁忌。

所以几乎所有文明都演化出对性器官的羞耻感，需要衣服遮盖。在有些文化中，这种规训非常严重，严重到宁可丢失生命也要所谓的贞洁。

现代社会的羞耻建立在规训之上，为个体建立羞耻感，是一种身份认同、确认社会秩序的工具。规训是组织演化过程的必要条件，如果不需要社会组织，羞耻也就不必要了。

=== 克服过度羞耻

羞耻本身并没有太多坏处，只是过度的羞耻会给人带来麻烦。我们需要有意识的去除掉过度规训带来的羞耻问题了。

在演讲俱乐部登台演讲，即使演讲的不好人们也不会批评你，这时候不需要感到羞耻，大胆演讲即可；但收费的演讲活动，如果演的不好，确实听众会扔臭鸡蛋，这时候的羞耻反而会保护你。

现代社会中，过度羞耻带来的利益损失，远远大于羞耻提供保护带来的好处。

例如有人失业了，出门去摆个摊，都会有人不好意思，感到羞耻。这本质的原因是，原本资源雄厚的家族，不需要做这种“低下”的工作，现在出去摆摊创业，会得到周围的人的评价、嘲笑。

但是这些嘲笑带来的伤害有多大呢？ 克服羞耻的方法是理解某些行为的后果并没有这么可怕。

尝试穿更加清凉的衣服，不会被批评和嘲讽，反而会得到夸奖，对穿衣的羞耻感就少了很多。 我们被规训为助人为乐，那么拒绝别人就会不好意思，原因是拒绝可能会带来批评。但是掂量一下，无脑接受别人带来的利益损失重要，还是被人批评重要呢？

=== 羞耻感正在减弱

现在社会的发展，羞耻感的正在减弱。

城市化的发展，人与人之间的长期联系减弱了，不再需要这么强烈的身份认同来换取生存资源。例如，在传统宗族文化中，因为逾越规则导致被族长批评，导致丢失很多工作机会，因为名声不好导致交友和求偶都受到影响。

随着城市化的发展，人们变得原子化、匿名化，名声对于生存来说，没那么重要了。法治的发展，代替了羞耻作为新的规训方式代替羞辱来建立社会秩序。

例如，只要在不触犯法律的情况下，即使穿得再暴露，也不会带来实质性的伤害，那么有暴露欲望（比如天气热？）的人就不会再感到羞耻。

甚至更进一步，如果突破羞耻会被鼓励或者带来好处呢？

第一个上台讲话的人即使错误百出，人们也都包容的称赞；扮丑来博眼球获得更多的粉丝，从而获得称赞。

总之，深刻理解羞耻感，把羞耻和利益拎清楚，在羞耻感不断降低的社会环境下，降低羞耻感，我们会不会过得更舒服一点？
