== 幸福为何短暂？幸福是对比出来的吗？

在前面的内容中，我们已经讨论过痛苦是什么，在讨论痛苦的时候顺便讨论了一下幸福是一种神经回路的奖励。那么我们是否有时候思考过一个问题，为什么痛苦很长，而幸福很短暂？

其实人们对幸福的感受也有生理基础，这个基础就是今天想要讨论的话题——跳变感受器。

什么是跳变感受器？

直白来说，人类大多数的感受器都是在感受信号的变化，而非信号本身。比如，对于温度而言，从炎热的环境进入空调房，感受到的是温度的变化，而如果一直待在空调房感受这种变化就很微弱。因为我们体温是恒定的，所以即使变化不剧烈也能感受到温度。

跳变感受器主要对刺激的变化敏感。它们在刺激开始和结束时反应迅速，但在持续的刺激中，其反应会快速适应或减少。这些受体对恒定的刺激不太敏感，会快速适应，从而不再发出信号。皮肤的触觉和压力感受器就是典型的跳变感受器。这些受体在你刚触摸到物体时会发出强烈信号，但如果触摸持续不变，它们的信号会迅速减弱。

我们在通信领域遇到类似的场景，信号是通过电流电平的高低来编码的，如果高电位代表 1 低电位代表 0，这很符合直觉。

但在实现上，检测高低电位很困难，所以通常使用电平的跳变来编码信号，这就是大名鼎鼎的曼彻斯特编码。

曼彻斯特编码是一种数字编码方案，通过在每个比特周期中间进行电平转换来表示比特的值：0 通常由低到高的跳变表示，而 1 由高到低的跳变表示。这种编码方式的核心特征是跳变，它确保了在每个比特周期中都有信号电平的变化。

因此，曼彻斯特编码的本质与跳变感受器非常相似，跳变感受器也是通过对刺激变化（而不是持续状态）的敏感性来感知环境。因为跳变感受器专注于检测变化，类似于曼彻斯特编码中的信号转换，它们能够以较低的能量成本和复杂性实现对信号的响应。

这种机制对比那些需要持续感知恒定刺激的系统来说，更加高效，因为它不需要对不变的背景进行处理，从而节省了资源。因此，跳变感受器的实现不仅在生物系统中具有优势，在技术系统如曼彻斯特编码中也具有重要意义，因为它们都依赖于对变化的快速响应，而非对静态信息的持续处理。

这个现象可以解释为什么我们感受到快乐的时间很短。小孩得到了想要的玩具，奖励回路就会开始启动，释放出幸福相关的激素，但是激素的受体往往不能持续感受到这种刺激，所以就无法体会到快乐了。

经过一段时间激素的代谢，感受器也恢复到先前的状态，神经系统又能建立新的反馈回路。正常情况下，生存和繁衍并不需要持续产生幸福感，基因并不在乎什么幸福感。

偶然的情况下，人类获得了外源物质的刺激，让神经系统莫名其妙的感到幸福，只需要不断提高外源物质，就能持续获得幸福感，这就是毒品的可怕之处。

从生物的长期生存策略上看，我们应该放弃持续的幸福感的幻想，接受偶尔的幸福感，并管理好奖励机制，这样就能通过组合短期的奖励回路，达到长期的目标。

=== 游戏上瘾的原理

跳变感受器和奖励系统能够解释电子游戏上瘾的原理。

电子游戏设计中一般会有这样几个关键的机制：

- 奖励系统：游戏中的成就、解锁新关卡、获得虚拟奖励等都能引发这种奖励回路。
- 变量奖励：由于固定的模式会导致玩家心理疲劳，所以加入更多的随机性，产生类似跳变的信号。
- 竞争: 通过多人在线竞技和计分板，触发人类从竞争中获胜的奖励机制，另外通过真人对抗，不确定性也会更强。

从某种程度上来说，电子游戏模拟了人类原始大脑的奖励系统，比如长期演化过程中依然保留下来的猎杀、竞速、生存和交友等奖励回路。这些也是人类本性的一部分，只不过现代社会需要约束它们，电子游戏恰好在模拟的环境下，将其释放出来了。

那么如何摆脱上瘾？我们无法通过平淡的事情让人代替原本已经存在的体验，只能通过寻找更加有意义的事情。 例如在现实中，完成一件更有挑战的事情，会比游戏获得的激励更强。

对于很多人来说，赚钱这个游戏，比手机上的游戏好玩得多，唯一的缺点是奖励迟不兑现，或者游戏难度过大。

=== 小心“心锚”

和跳变感受器的工作机制类似的心理现象是“心锚”，出现一些我们觉得困惑的事情都和“心锚”相关。

但“心锚”和跳变感受器是否有关，我还不得而知，不过“心锚”也会对幸福感产生类似的比较效应。

心锚是一个心理学术语，指的是在决策过程中，人们会依赖于某一个初始信息或数值（锚点）来进行判断。这个锚点会显著影响后续的思维和决策，即使这个锚点可能是随机的或不相关的。心锚效应是认知偏见的一种表现，在判断、估计和决策时经常出现。

假设一个人今年的收入增加了10%，而过去几年他的收入一直保持稳定。这次的收入增长成为他的锚点。这个人开始评估自己的幸福感，并感到更幸福，因为他将当前的收入增长与过去几年的收入水平进行比较。这个初始增长（锚点）为他的幸福感提供了一个积极的基准。

然而，他得知他的同事今年收入增长了20%。这个新信息成为一个新的锚点，导致他重新评估自己的幸福感。由于新的比较锚点，他可能会觉得自己的收入增长不如他人，从而降低了他的相对幸福感，即使他原本对10%的增长感到满意。

在这个例子中，即使这个人是一个非常理性的人，但依然逃不过“心锚”的影响，因为我们在前面讨论过人脑的分裂特性，大脑理性的区域无法完全管理感性的区域，他需要不断暗示自己才能接受这一切。

“心锚”在情感关系中的影响也非常大。

一对恋人在初次约会时，男友精心安排了一个浪漫的晚餐，并在晚餐中展示了幽默感和体贴。这些特质成为女友对男友的心锚。女友在接下来的关系中，将浪漫和幽默作为衡量男友及关系质量的标准。

随着时间的推移，伴侣在其他方面的表现可能有所波动，例如工作压力导致对方暂时不再表现出初期的浪漫和幽默。

因为初始印象深刻，当这些特质不再明显时，个体可能会感到失望，甚至怀疑关系的质量，因为他一直以这些特质作为衡量关系幸福感的基准。

=== 从平淡中获得幸福

看起来只有刺激和随机事件才能让人获得幸福。 能在平淡的生活中获得幸福吗？

也许很难，也许需要时间让神经受体恢复到原来的状态，也许永远回不到童年的幸福感了，因为对于小孩来说，任何体验都是新奇的。

不过我们能做的是，去经历生活中的各种事情，拥抱生活中随机的事件，留意感受生活的跳变。 幸福感就是在大雨淋湿后跑到房间，在冰天雪地的冬天躲在屋子里取暖，在疲惫旅途之后看到的绿意盎然。

我们也能找到长期的目标，将其拆解为段落，在每一步的前进中感受跳变。
