== 如何不被操控？

你是否听过这样的对话。

老板：“你怎么这个月业绩不达标”
员工：“这个月经济不好，整个行业都在下滑”
老板：“为什么不和业绩好的人比一比，销冠都可以做到，你做不到。”
老板：“为什么不和业绩好的人比一比，销冠都可以做到，你做不到。”

按照时下流行的话说，这是一段典型的 “PUA” 对话。 然而 PUA 的原始含义并非如此，和 PUA 这个词更近的词叫做“gaslighting” 也就是煤气灯效应。

简单来说，人们通过心理暗示或者话语技术，实现对他人的打压、控制和意识形态影响，从而达成自己的目的。通常这种行为都是损害对方利益，而对自己有利的。 煤气灯效应这个词来源于 1938 年的剧本《煤气灯》（Gas Light），后来改编成电影，其中一名角色通过操纵家中的煤气灯来让另一名角色怀疑自己的感官。

我费了好⼤劲才找到了“操控（manipulation）”这个词，能概括人类世界中各种情感打压、欺骗、规训、意识形态培养。

深入操控这个词，你可能会对“人性本善”的幻想打破。按照我们前面说的多细胞生物的存在方式，海绵动物的食物细胞获得食物并消化后，会把营养分给其它细胞，让整个机体能运转下去。

但人类联盟的这个层面，要复杂得多，建立联盟需要取得平衡。 操控可以看做是竞争和博弈的一种手段，这种行为是联盟取得平衡的一种方式，因为人类的竞争性是来自于基因，不因联盟的建立而消失，只不过被约束了起来。

操控就是在联盟的契约规则之内，微妙的竞争，甚至发生在上一篇文章中的最里层的亲子联盟中。 PS：甚至人类会操控自己。

把操控这个词落地到实际的场景中，就是忽悠、洗脑、广告、欺骗和诈骗。

=== 随处可见的操控

我们再看一下我们的联盟，来找一找没有被我们发现的操控。

- 社交联盟：当你不那么熟的朋友要求你借钱给他的时候，他会说“你怎么这么小气”，这是一种典型的通过道德感来实现的操控。
- 两性联盟：你的女朋友让你去洗碗，你不愿意去，她可能会说“你是不是不爱我了”。
- 亲子联盟：当你的父母希望填报他们觉得满意的高考专业志愿时，他们会说，“这都是为你好”。

是否感到血压上来了，但当处于这种环境下时，往往意识不到自己正在被操控。

诡谲的是，越是在自己联盟圈的联盟者发起操控，人们就越难识别到。因为前面我们讨论过神经系统的缓存机制，人们倾向于信任已经建立的神经回路。

所以历史上的智谋家认为，敌人并不可怕，因为你已经知道他是敌人，而伪装成朋友的敌人更令人畏惧，因为对他们不设防。

不过和帝王将相相比，普通人的利益不值得被人付出巨大的技巧来操控，并没有多少东西值得失去。

=== NLP：人脑是一些程序

为什么我们容易被操控？因为我们反复强调，我们的意识不过就是一些神经回路而已。 这些神经回路就像一个一个程序，它们互相调用和依赖。

我们接受了道德这个程序，在长时间的教育中，这个程序已经存在良久。 那么操控者只需要使用道德的高地来操控他人，让他人在道德迷思中放弃利益。

说难听一点，这个过程和训练宠物并没有本质区别。

我们应该都知道巴普洛夫的实验，他是俄罗斯著名的生理学家，他因对条件反射的研究而闻名，尤其是他的经典的“巴普洛夫训狗实验”，这项实验开创了行为主义心理学的先河。

虽然他初期并不是为了研究心理学而是对狗的消化系统进行研究。巴普洛夫选用狗作为实验动物，并在实验室环境中进行控制。他给狗安装了可以测量唾液分泌量的装置，以便观察和记录反应。

在每次给狗喂食前，巴普洛夫都会敲响铃声。起初，狗只是在看到食物时流口水，经过多次重复后，狗开始在听到铃声时自动流口水，即使食物尚未出现。这是因为狗将铃声与即将到来的食物联系起来了。

天啦！这和人类中的操控技术多么相似。

在广告领域，经典条件反射的原理被广泛应用，以影响消费者的购买决策。

可口可乐在 20 世纪 30 年代推出了一系列与圣诞节相关的广告，这些广告中会出现和节日相关的圣诞老人形象。

在这些广告中，圣诞老人形象最初只是一个节日的象征，不会直接引发对可口可乐的购买欲望。然而，它在广告中反复出现，与节日的欢乐气氛联系在一起。

可口可乐作为一种饮料，其本身是广告中的非条件刺激，它能够引发消费者的实际口渴和饮用欲望。与圣诞节的愉快氛围结合，使其在广告中具有了特殊的吸引力。

经过反复的广告展示，消费者会将圣诞老人和节日的快乐情感与可口可乐的品牌联系起来。每当看到圣诞老人形象或听到与圣诞节相关的音乐时，消费者就会自然而然地联想到可口可乐，并产生购买欲望。

为了研究人脑中的这些模式，有人提出了神经语言程序学（Neuro-Linguistic Programming, NLP），虽然我们还无法完全确定 NLP 背后的生理基础（所以某些心理学家不承认 NLP 的科学性），但这个理论能解释操控这件事，并在日常生活中被应验。

NLP 理论认为，人类的感知和行为是通过大脑的神经系统来实现的，而这个过程非常依赖语言，语言本身不仅是沟通的工具，还会影响人的思维，这个完成的过程就像一个计算机程序。所以我们通过语言接收信息、思考和决策的过程，会形成一些神经回路，这些神经回路是依赖语言的，那么就可以通过语言干预人的思维，实现操控。

比如销售员可以通过 NLP 来操控成交。销售员在给顾客介绍两个产品后，顾客依然在犹豫。往往有经验的销售员会这样说，“我们是要这个还是另外一个呢？”

其实这句话并不符合逻辑，因为顾客还没有决定要买，不过人脑会根据经验来修正逻辑性（这可能具有某种进化意义），所以顾客大脑中被植入了一个程序“我已经决定要买了，现在只需要选择 A 还是 B”。

虽然这种方法不一定每次都成功，但足够有效，成为了销售员的惯用伎俩，这种技巧在 NLP 理论中，被叫做语言模式，因为人们往往大脑中存在一些固定的模式，让这些模式触发就能实现操控。在这个场景中，人脑的模式就是 “决定要买了，再决定买哪一个”。

类似的 NLP 技巧还有重新定义，这种技巧是很多人无意识之间使用的（确实很多操控行为发生，人们都不知道自己在操控别人，操控几乎是人类的本能了）。

例如当顾客对产品价格表示担忧时，销售员可以重新定义价格说：“虽然价格看起来有些高，但你要考虑到这款产品的长期使用价值和节省的时间。” 这是一种逻辑上的偷换概念，把顾客的关于价格的定义悄悄调整了，只不过非常隐晦。

这里我给一个明显的偷换概念的例子感受一下。假设有两个人 A B 在辩论专注力的问题：

A：人不能同时看数学书和语文书。
B：哪为什么我能同时学习数学和语文两个科目呢？

显然人们没有意识到 “同时” 的定义存在问题，在 A 的定义中，同时可能是一个小时内，而 B 的同时，可能跨越一个学期。

=== 如何让自己不被操控

这里我不想传授 NLP 知识和操控术（因为我也不会），我只是想说表达我们对自己的认识远远不足，以至于经常受到操控、欺骗，带来痛苦。

而这里的操控还属于个体的操控，我还说过我们处在无处不在的操控之中，这就是对群体的操控，这是一个，它涉及道德、意识形态等更宏大的话题，不过深刻理解操控能让我们理解这这个世界的游戏规则。

要进一步理解操控，已经超出人生的基本问题了，更多和社会规则有关，有机会我会在以后写一些组织、社会规则的内容，和大家探讨这个世界的游戏规则，这些游戏规则包括善恶、道德和秩序。

人类语言不是精确的，到处都是漏洞，很容易发生 NLP 注入（不好意思，这里我又发明了一个新词）。 通过 NLP 注入，人们就能实现操控，无论是有意识还是无意识的。

为了抵御 NLP 注入，一方面需要了解我们前面讨论的人类的特点，也需要了解常见的 NLP 操控技巧，但更重要的是**学习逻辑学。**

逻辑学提供了系统化的思维工具和原则，这些工具可以帮助我们分析信息、识别虚假论证和不合理的影响策略，操控某种程度上和逻辑学中的诡辩不谋而合。 诡辩是通过逻辑漏洞驳斥对方观点，而操控是通过语言操控对方的决策，看起来操控危害更大一些。

逻辑学中有很多经典的谬误，例如销售员让顾客选择 A 还是 B 本质是一个虚假两难谬误，因为顾客可以选择不买。

还有一个例子是滑坡谬误。例如学校通过操控的方式让孩子不要在学校玩手机，会这样说：如果我们允许学生在校园内使用手机，那么他们将会越来越频繁地使用手机，最终他们将完全依赖手机，不再专注于学业。这将导致他们的学习成绩下降，甚至整个学校的教育质量会变得糟糕。

在这个例子中，允许学生使用手机被错误地推断会导致一系列极端的负面后果。这个论证忽略了现实中可能有其他干预措施和管理策略来平衡手机使用与学业之间的关系。

因为玩手机只是影响学业的一种潜在的原因，并不能完全证明，只要玩手机就会成绩下滑。

当然，我们不能让所有人都具有高超的逻辑学技巧，还有一个比较可行的方式就是捂住自己的钱包，无论操控怎么发生，涉及真实利益变化的时候，总是需要谨慎一点。

PS：要想抵御操控很难，那就训练自己不要变成一个容易上头的人（这算不算一种修行呢？）。

=== 补充：动物世界中的操控术

操控并不是人类的专属，欺骗存在于整个动物世界。

在动物世界中，操控术可以认为是通过行为、策略或伪装来影响其他动物的行为以获取利益。和人类这种天生的操控家比起来，动物世界中的操控大部分非常拙劣，虽然也有一些“精湛的操控技艺”出现。

有一些属于伪装流。

变色龙能够改变皮肤颜色以匹配周围环境，从而避免被捕食者发现或接近猎物；枯叶蝶的翅膀在闭合时看起来像枯叶，包括叶脉和斑点，这使它在森林地面上几乎不可见。

而另外一些属于欺骗流。

杜鹃鸟通过将自己的蛋放在其他鸟类的巢中，让这些养父母鸟为其孵化和抚养后代。杜鹃的蛋通常与宿主鸟的蛋相似，以降低被发现的风险；有些蛇头鱼会模仿清洁鱼的行为接近其他鱼类，但实际上是为了撕咬它们身上的鳞片和肉。
